name: PandoraCore
version: ${project.version}
main: dev.minecraftplugin.pandoracore.PandoraCore
softdepend: [ UltraPermissions, Factions, FAIO-Factions-All-In-One ]
authors: [ X1XX, ProNanigans ]
description: Pandora Core
