name: PandoraCore
version: ${project.version}
main: dev.minecraftplugin.pandoracore.PandoraCore
authors: [ X1XX, ProNanigans ]
description: Pandora Core
permissions:
  pandoracore.patchmanager:
    description: Allows you to access the patch manager.
